"""empty message

Revision ID: 25f2540fe843
Revises: 434420c3ab73
Create Date: 2023-07-03 13:01:22.057176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f2540fe843'
down_revision = '434420c3ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Float(precision=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
