"""empty message

Revision ID: 68945dee5c59
Revises: b1e042d64e69
Create Date: 2023-07-03 18:15:05.359072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68945dee5c59'
down_revision = 'b1e042d64e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('cat_price',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('cat_price',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
