"""empty message

Revision ID: 7cf38dd0e59b
Revises: b17c9e614b4a
Create Date: 2023-07-08 16:34:09.794513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cf38dd0e59b'
down_revision = 'b17c9e614b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_package_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'package', ['user_package_id'], ['package_id'])
        batch_op.drop_column('user_package')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_package', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'package', ['user_package'], ['package_id'])
        batch_op.drop_column('user_package_id')

    # ### end Alembic commands ###
