"""empty message

Revision ID: b1e042d64e69
Revises: 91af8a4d3a96
Create Date: 2023-07-03 14:16:28.511894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1e042d64e69'
down_revision = '91af8a4d3a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.String(length=100),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
